name: deploy-docC-on-github-page

on:
  workflow_dispatch

env:
  repo_name: ${{ github.event.repository.name }}
  xcodebuild_derivedData: ".derivedData"
  doc_path: "docs"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-26
    steps:
      - name: Package names
        run: echo "Generate DocC for ECommerceApp, OrderManagement, ProductCatalog, and UserManagement packages at ${{ env.repo_name }}"
      - name: Checkout Action
        uses: actions/checkout@v6
      - name: Create docs directory
        run: mkdir -p ${{ env.doc_path }}
      - name: Build DocC for ECommerceApp
        run: |
          xcodebuild docbuild -scheme ECommerceApp -derivedDataPath ${{ env.xcodebuild_derivedData }} -destination 'generic/platform=iOS';
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting ${{ env.xcodebuild_derivedData }}/Build/Products/Debug-iphoneos/ECommerceApp.doccarchive \
            --output-path ${{ env.doc_path }}/ecommerceapp \
            --hosting-base-path ${{ env.repo_name }}/ecommerceapp;
      - name: Build DocC for OrderManagement
        run: |
          xcodebuild docbuild -scheme OrderManagement -derivedDataPath ${{ env.xcodebuild_derivedData }} -destination 'generic/platform=iOS';
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting ${{ env.xcodebuild_derivedData }}/Build/Products/Debug-iphoneos/OrderManagement.doccarchive \
            --output-path ${{ env.doc_path }}/ordermanagement \
            --hosting-base-path ${{ env.repo_name }}/ordermanagement;
      - name: Build DocC for ProductCatalog
        run: |
          xcodebuild docbuild -scheme ProductCatalog -derivedDataPath ${{ env.xcodebuild_derivedData }} -destination 'generic/platform=iOS';
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting ${{ env.xcodebuild_derivedData }}/Build/Products/Debug-iphoneos/ProductCatalog.doccarchive \
            --output-path ${{ env.doc_path }}/productcatalog \
            --hosting-base-path ${{ env.repo_name }}/productcatalog;
      - name: Build DocC for UserManagement
        run: |
          xcodebuild docbuild -scheme UserManagement -derivedDataPath ${{ env.xcodebuild_derivedData }} -destination 'generic/platform=iOS';
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting ${{ env.xcodebuild_derivedData }}/Build/Products/Debug-iphoneos/UserManagement.doccarchive \
            --output-path ${{ env.doc_path }}/usermanagement \
            --hosting-base-path ${{ env.repo_name }}/usermanagement;
      - name: Copy index page
        run: cp .github/workflows/index.html ${{ env.doc_path }}/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.doc_path }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
